name: Deploy to Vercel (main)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: vercel-deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install

      - name: Pull Vercel environment (production)
        run: bunx vercel pull --yes --environment=production

      - name: Build (Vercel)
        run: bunx vercel build --prod

      - name: Deploy to Vercel (Production)
        id: vercel_deploy
        run: |
          set -o pipefail
          output=$(bunx vercel deploy --prebuilt --prod)
          echo "$output"
          url=$(echo "$output" | grep -Eo 'https://[a-zA-Z0-9._-]+\.vercel\.app[^ ]*' | tail -n 1 || true)
          echo "url=${url}" >> $GITHUB_OUTPUT

      - name: Post deployment summary
        if: always()
        run: |
          {
            echo "## Vercel Deployment";
            echo "";
            echo "**Status**: ${{ job.status }}";
            echo "**URL**: ${{ steps.vercel_deploy.outputs.url }}";
          } >> $GITHUB_STEP_SUMMARY
